spring.datasource.url=jdbc:mysql://localhost:3306/honeychainprototype
spring.datasource.username=root
spring.datasource.password=1707
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# TODO: move to env var before any deployment/demo submission
jwt.secret=change_this_to_a_long_random_string_before_using_in_prod
jwt.expiration-ms=86400000
app.public-base-url=http://localhost:5173